v6
VirgilSecurity/crypto-php pull request #9
Opened 2019-11-20 14:07 UTC by PetrenkoAnton

2020-03-23 10:38 UTC, nau11713 submitted a review, later dismissed

2020-03-25 11:53 UTC, SanjoDeundiak requested changes

2020-03-25 11:53 UTC, SanjoDeundiak commented on src/Services/VirgilCryptoService.php
> +            $keyProvider = new KeyProvider();
Copy&paste from importInternalPublicKey

2020-03-31 10:24 UTC, nau11713 submitted a review, later dismissed

2020-03-31 10:29 UTC, SanjoDeundiak requested changes

2020-03-31 10:29 UTC, SanjoDeundiak commented on src/Core/Stream.php
> +        var_dump(123);
what's that?

2020-03-31 10:29 UTC, SanjoDeundiak commented on src/Core/IO/StreamInterface.php
> +    public function getInput(): string;
Why would StreamInterface have getInput and getOutput and what they return?

2020-04-02 14:14 UTC, SanjoDeundiak approved these changes

2020-04-02 15:05 UTC, merged